# Generated by Django 3.1.2 on 2021-02-14 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('open', models.DecimalField(decimal_places=4, max_digits=4)),
                ('high', models.DecimalField(decimal_places=4, max_digits=4)),
                ('low', models.DecimalField(decimal_places=4, max_digits=4)),
                ('close', models.DecimalField(decimal_places=4, max_digits=4)),
                ('volume', models.IntegerField()),
                ('api_date', models.DateField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_maker.stock')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
