# Generated by Django 3.1.2 on 2021-03-05 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_details',
            field=models.TextField(default='{}'),
        ),
        migrations.CreateModel(
            name='IndicatorCalculationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator', models.CharField(choices=[('STOCHASTIC', 'STOCHASTIC'), ('RSI', 'RSI'), ('MACD', 'MACD'), ('ADR', 'ADR')], max_length=100)),
                ('operation_data', models.TextField(default='{}')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_maker.stock')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
