# Generated by Django 3.1.2 on 2021-03-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0002_auto_20210305_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldata',
            name='adr',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='macd',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='rsi',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='stochastic',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='close',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='high',
            field=models.DecimalField(decimal_places=20, max_digits=20),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='low',
            field=models.DecimalField(decimal_places=20, max_digits=20),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='open',
            field=models.DecimalField(decimal_places=20, max_digits=20),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='volume',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=20),
        ),
    ]
