# Generated by Django 3.1.2 on 2021-03-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0004_auto_20210313_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldata',
            name='adr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='close',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='high',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='low',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='macd',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='open',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='rsi',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='stochastic',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='volume',
            field=models.FloatField(default=0.0),
        ),
    ]
