# Generated by Django 3.1.2 on 2021-03-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0005_auto_20210313_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldata',
            name='api_date',
            field=models.DateTimeField(),
        ),
    ]
