# Generated by Django 3.1.2 on 2021-03-16 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0006_auto_20210313_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldata',
            name='macd',
        ),
        migrations.RemoveField(
            model_name='historicaldata',
            name='stochastic',
        ),
        migrations.CreateModel(
            name='StochasticIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('k_low', models.FloatField(default=0.0)),
                ('k_fast', models.FloatField(default=0.0)),
                ('api_date', models.DateTimeField()),
                ('historical_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_maker.historicaldata')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MACDIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('macd', models.FloatField(default=0.0)),
                ('signal', models.FloatField(default=0.0)),
                ('api_date', models.DateTimeField()),
                ('historical_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_maker.historicaldata')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
