# Generated by Django 3.1.2 on 2021-03-16 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0008_auto_20210316_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stochasticindicator',
            old_name='k_low',
            new_name='k_slow',
        ),
    ]
