# Generated by Django 3.1.2 on 2021-03-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0009_auto_20210316_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldata',
            name='k_fast',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='k_slow',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='macd',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='signal',
            field=models.FloatField(default=0.0),
        ),
    ]
