# Generated by Django 3.1.2 on 2021-03-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0010_auto_20210317_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldata',
            name='bullet',
            field=models.CharField(choices=[('START', 'START'), ('STOP', 'STOP'), ('PAUSE', 'PAUSE'), ('EMPTY', 'EMPTY')], default=('EMPTY', 'EMPTY'), max_length=20),
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='f_macd',
            field=models.CharField(choices=[('HIGH', 'HIGH'), ('LOW', 'LOW'), ('EMPTY', 'EMPTY')], default=('EMPTY', 'EMPTY'), max_length=20),
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='f_rsi',
            field=models.CharField(choices=[('HIGH', 'HIGH'), ('LOW', 'LOW'), ('EMPTY', 'EMPTY')], default=('EMPTY', 'EMPTY'), max_length=20),
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='f_stoch',
            field=models.CharField(choices=[('HIGH', 'HIGH'), ('LOW', 'LOW'), ('EMPTY', 'EMPTY')], default=('EMPTY', 'EMPTY'), max_length=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='priority',
            field=models.CharField(choices=[('LOW', 'LOW'), ('MED', 'MEDIUM'), ('HIGH', 'HIGH')], default=('HIGH', 'HIGH'), max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='high',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='low',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='open',
            field=models.FloatField(default=0.0),
        ),
    ]
