# Generated by Django 3.1.2 on 2021-03-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0011_auto_20210326_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldata',
            name='bullet',
            field=models.CharField(default=('EMPTY', 'EMPTY'), max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='f_macd',
            field=models.CharField(default=('EMPTY', 'EMPTY'), max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='f_rsi',
            field=models.CharField(default=('EMPTY', 'EMPTY'), max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='f_stoch',
            field=models.CharField(default=('EMPTY', 'EMPTY'), max_length=20),
        ),
    ]
