# Generated by Django 3.1.2 on 2021-04-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0012_auto_20210326_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'HIGH'), ('LOW', 'LOW'), ('MED', 'MEDIUM')], default=('HIGH', 'HIGH'), max_length=20),
        ),
    ]
