# Generated by Django 3.1.2 on 2021-04-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0013_auto_20210406_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldata',
            name='api_date',
            field=models.DateTimeField(unique=True),
        ),
    ]
