# Generated by Django 3.1.2 on 2021-04-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0014_auto_20210413_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldata',
            name='api_date',
            field=models.DateTimeField(),
        ),
    ]
