# Generated by Django 3.1.2 on 2021-05-15 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0016_historicaldata_k'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTransactionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_market', models.IntegerField(default=0)),
                ('status', models.CharField(default='close', max_length=100)),
                ('stop_loss_price', models.FloatField(default=0.0)),
                ('take_profit_price', models.FloatField(default=0.0)),
                ('avg_price', models.FloatField(default=0.0)),
                ('entry_type', models.CharField(default='', max_length=100)),
                ('number_of_entry', models.IntegerField(default=0)),
                ('historical_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report_maker.historicaldata')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
