# Generated by Django 3.1.2 on 2021-05-20 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0017_historicaltransactiondetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransactiondetail',
            name='historical_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_maker.historicaldata'),
        ),
    ]
