# Generated by Django 3.1.2 on 2021-05-21 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0018_auto_20210520_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransactiondetail',
            name='historical_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report_maker.historicaldata'),
        ),
    ]
