# Generated by Django 3.1.2 on 2021-06-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0019_auto_20210521_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransactiondetail',
            name='closing_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='historicaltransactiondetail',
            name='earning_losing_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='historicaltransactiondetail',
            name='entry_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='historicaltransactiondetail',
            name='transaction_id',
            field=models.IntegerField(null=True),
        ),
    ]
