# Generated by Django 3.1.2 on 2021-06-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0020_auto_20210602_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldata',
            name='adr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='close',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='high',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='k',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='k_fast',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='k_slow',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='low',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='macd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='open',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='rsi',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='signal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicaltransactiondetail',
            name='avg_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicaltransactiondetail',
            name='closing_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactiondetail',
            name='earning_losing_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactiondetail',
            name='entry_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactiondetail',
            name='stop_loss_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicaltransactiondetail',
            name='take_profit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicaltransactiondetail',
            name='transaction_id',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='macdindicator',
            name='macd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='macdindicator',
            name='signal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stochasticindicator',
            name='k_fast',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stochasticindicator',
            name='k_slow',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
