# Generated by Django 3.1.2 on 2021-06-02 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0020_auto_20210602_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidatedTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('net_profit', models.FloatField(default=0.0)),
                ('gross_profit', models.FloatField(default=0.0)),
                ('gross_loss', models.FloatField(default=0.0)),
                ('profit_factor', models.FloatField(default=0.0)),
                ('total_closed_trades', models.FloatField(default=0.0)),
                ('total_open_trades', models.FloatField(default=0.0)),
                ('number_winning_trades', models.FloatField(default=0.0)),
                ('number_losing_trades', models.FloatField(default=0.0)),
                ('percent_profitable', models.FloatField(default=0.0)),
                ('average_trade', models.FloatField(default=0.0)),
                ('average_winning_trade', models.FloatField(default=0.0)),
                ('average_losing_trades', models.FloatField(default=0.0)),
                ('ratio_avg_win_avg_loss', models.FloatField(default=0.0)),
                ('largest_winning_trades', models.FloatField(default=0.0)),
                ('largest_losing_trade', models.FloatField(default=0.0)),
                ('avg_bars_winning', models.FloatField(default=0.0)),
                ('avg_bars_losing', models.FloatField(default=0.0)),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_maker.stock')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
