# Generated by Django 3.1.2 on 2021-06-04 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0022_auto_20210604_0118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltransactiondetail',
            old_name='number_of_entry',
            new_name='number_of_unities',
        ),
    ]
