# Generated by Django 3.1.2 on 2021-06-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0023_auto_20210604_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolidatedtransactions',
            name='stock_id',
            field=models.IntegerField(default=0),
        ),
    ]
